version: "3.3"
services:
  backend:
    image: jerin07/finance-tracker:latest
    ports:
      - "9191:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "8081:80"
      - "8125:8125/udp"
      - "8125:8125/tcp"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8080"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"

